# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6ad40c5288af92b93d6c548ce212f22d69e63d72a28d95ec5d747b16e71e90276c30f34ae89920f4892367d3bcd1561539a97e493d0324e0026c0cc367d12b5

test:
  secret_key_base: 02736641cbf13585f95004aa9abdd778342a581b492e5884b87b5c1a3a600ac7783867c8d789fa339b2a5005365218659fec949b9354024356867deeb2acf691

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
